export const initialLessons = () => [
{ id: "basico-movimento-retilineo", title: "Introdução ao movimento retilíneo", level: "basico", topics: ["movimento-retilineo", "vetores"], description: "Conceitos fundamentais de movimento em linha reta, posição, deslocamento, velocidade média e vetores de posição.", videoUrl: "https://www.youtube.com/embed/DVbFzPVfCbY", interactiveUrl: "", downloads: [], exercises: "" },
{ id: "basico-mru", title: "Movimento Retilíneo Uniforme (MRU)", level: "basico", topics: ["mru", "movimento-retilineo"], description: "Velocidade constante, equações horárias e gráficos posição x tempo.", videoUrl: "https://www.youtube.com/embed/KqjjhxEgjyE", interactiveUrl: "", downloads: [], exercises: "" },
{ id: "intermediario-mruv", title: "Movimento Retilíneo Uniformemente Variado (MRUV)", level: "intermediario", topics: ["mruv", "movimento-retilineo"], description: "Velocidade variável, aceleração constante e equações do MRUV.", videoUrl: "https://www.youtube.com/embed/CI7v8672Bik", interactiveUrl: "", downloads: [], exercises: "" },
{ id: "intermediario-vetores", title: "Vetores na cinemática", level: "intermediario", topics: ["vetores"], description: "Deslocamento, velocidade e aceleração vetoriais; soma e decomposição.", videoUrl: "", interactiveUrl: "https://phet.colorado.edu/sims/html/vector-addition/latest/vector-addition_en.html", downloads: [], exercises: "" },
{ id: "avancado-movimento-circular", title: "Movimento circular e aceleração centrípeta", level: "avancado", topics: ["movimento-circular"], description: "Velocidade angular, frequência e aceleração centrípeta.", videoUrl: "https://www.youtube.com/embed/UMp7n-DVnUo", interactiveUrl: "", downloads: [], exercises: "" },
{ id: "avancado-lancamento-obliquo", title: "Lançamento oblíquo de projéteis", level: "avancado", topics: ["lancamento-obliquo", "mru", "mruv", "vetores"], description: "Decomposição em duas dimensões; alcance, altura máxima e tempo de voo.", videoUrl: "https://www.youtube.com/embed/6WGZGPjqI_8", interactiveUrl: "", downloads: [], exercises: "" }
];
export const initialQuizzes = () => [
{ id: "quiz-mru", lessonId: "basico-mru", question: "Em um MRU, qual afirmação é verdadeira?", options: { A: "A velocidade varia com o tempo.", B: "O deslocamento é sempre nulo.", C: "A velocidade é constante e diferente de zero.", D: "A aceleração é constante e diferente de zero." }, correct: "C", explanation: "No MRU a velocidade é constante e a aceleração é nula." },
{ id: "quiz-mruv", lessonId: "intermediario-mruv", question: "No MRUV, o gráfico velocidade x tempo é:", options: { A: "Reta horizontal", B: "Reta inclinada", C: "Parábola", D: "Qualquer curva" }, correct: "B", explanation: "A aceleração constante implica variação linear da velocidade." },
{ id: "quiz-lancamento", lessonId: "avancado-lancamento-obliquo", question: "No lançamento oblíquo sem ar, a aceleração é:", options: { A: "Horizontal e constante", B: "Vertical e constante para baixo", C: "Nula no vértice", D: "Variável em módulo" }, correct: "B", explanation: "A única aceleração é a gravidade, vertical para baixo." }
];
